@startuml Schullandheim
left to right direction
actor "Lehrer" as fc
actor "Mitarbeiter" as ma
rectangle Website_Schullandheim {
  usecase "Aufenthalt buchen" as UC1
  usecase "Aufenthalt einsehen/ändern" as UC_Auf_ans
  usecase "Nutzerkonto anlegen" as UC2
  usecase "Passwort setzen/zurücksetzen" as UC_PW
  usecase "Schul-/Klassendaten pflegen" as UC_Daten
  usecase "Kundendaten ansehen/bearbeiten" as UC_KUNDE
  usecase "Belegungsplan anzeigen lassen" as UC_BELEGPLAN

  (UC_Auf_ans) .> (UC1) : extends
  (UC_PW) .> (UC2) : extends
}
fc --> UC1
fc --> UC2
fc --> UC_Daten
'fc --> UC_PW
'fc --> UC_Auf_ans


note "Extension Point: Aufenthalt gebucht"  as N2 
(UC_Auf_ans) <<-- N2

ma --> UC_KUNDE
ma --> UC_BELEGPLAN
@enduml
